Feature/carousel
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a pull request #20
Opened 2023-10-10 08:42 UTC by Justicesvr

2023-10-10 14:33 UTC, YDrogen commented on src/api.jsx
Le `AbortController` ne sert à rien ici, il doit être initialisé dans le `useEffect` où on appelle `controller.abort()`

2023-10-10 14:34 UTC, YDrogen commented on src/pages/Artist.jsx
> +  const [search, setSearch] = useState('Karl Wirsum');
Est-ce normal la valeur par défaut ? Que se passe-t-il si rien n'est écrit ?

2023-10-10 14:35 UTC, YDrogen commented on src/pages/Artist.jsx
> +  const artistName = artworks.length > 0 ? artworks[0].artist_display : '';
Tu peux utiliser la syntaxe `?.` [(doc)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) pour raccourcir un peu la ligne

2023-10-10 14:36 UTC, YDrogen commented on src/pages/Artist.jsx
> +    let result = n % m;
Pourquoi `let` ?

2023-10-10 14:36 UTC, YDrogen commented on src/pages/Artist.jsx
> +      console.log(index);
`console.log` oublié

2023-10-10 14:36 UTC, YDrogen commented on src/pages/Artist.jsx
> +  console.log(artworks);
idem

2023-10-10 14:38 UTC, YDrogen commented on src/pages/Artist.jsx
> +      <div className="container w-full h-full">
class `container` utilisée ?

2023-10-10 14:38 UTC, YDrogen commented on src/pages/Artist.jsx
> +        <div className="carousel flex items-center w-full h-full">
class `carousel` utilisée ?

2023-10-10 14:38 UTC, YDrogen commented on src/pages/Artist.jsx
> +              className = 'card card--active opacity-100 z-[99] scale-100';
toutes les classes `card` `card--active` ... utilisées ?

2023-10-10 14:40 UTC, YDrogen commented on src/pages/Artist.jsx
> +  const mod = (n, m) => {
Il faudrait utiliser des termes plus parlants, on ne comprend pas ce que fait cette fonction

2023-10-10 14:43 UTC, YDrogen commented on src/pages/Artist.jsx
> +            const indexRight3 = mod(index + 2, artworks.length);
* Tout ça peut être sorti hors du `return` du component. (Ça n'apporte rien dans le `map`)
* Si le `artworks.length` est envoyé à chaque fois, pourquoi ne pas l'utiliser directement dans la fonction `mod` ?

2023-10-10 14:48 UTC, YDrogen commented on src/pages/Artist.jsx
> +            }
Tout ça, il faudrait le sortir hors du map également, il y a trop de code ici.
Essayer plusieurs paliers ?
```jsx
// si carte principale
// -> opacity-100, z-[99], ...

// sinon si carte juste derrière
// alors opacity 90, ...

// sinon si carte encore après
// ...

// ...
```

2023-10-11 08:41 UTC, Abecker37 submitted a review, later dismissed

2023-10-11 08:59 UTC, YDrogen requested changes

2023-10-11 08:59 UTC, YDrogen commented on src/components/NavBar.jsx
> +      <div className="group  relative flex cursor-pointer justify-center">
```suggestion
      <div className="group relative flex cursor-pointer justify-center">
```
Attenzione aux double espaces

2023-10-11 12:06 UTC, greegouze approved these changes

2023-10-11 16:26 UTC, YDrogen approved these changes

2023-10-11 16:26 UTC, merged