Feature/side effects
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a pull request #21
Opened 2023-10-10 14:48 UTC by greegouze

2023-10-10 14:49 UTC, jaalazard approved these changes

2023-10-10 15:04 UTC, Justicesvr approved these changes

2023-10-10 15:30 UTC, YDrogen requested changes

2023-10-10 15:30 UTC, YDrogen commented on src/components/Item.jsx
> +      <div>
Pourquoi une div ?

2023-10-10 15:30 UTC, YDrogen commented on src/components/NavBar.jsx
> +      setNavisible(true);
Il manque une lettre

2023-10-10 15:30 UTC, YDrogen commented on src/components/NavBar.jsx
> +            <motion.nav
`nav` n'est pas le bon choix ici, on est déjà dans une `nav`

2023-10-10 15:30 UTC, YDrogen commented on src/components/NavBar.jsx
> +          <div className="group  relative flex cursor-pointer justify-center">
```suggestion
          <div className="group relative flex cursor-pointer justify-center">
```
Deux espaces

2023-10-10 15:30 UTC, YDrogen commented on src/components/NavBar.jsx
> +              <motion.div className={`${effect}`} variants={sidebar} />
Pourquoi pas juste `={effect}` ?

2023-10-10 15:30 UTC, YDrogen commented on src/components/NavBar.jsx
> +              className=" h-10 w-10 rounded-full p-4 opacity-0 shadow outline-none transition-all duration-500 ease-in-out  group-hover:w-28  group-hover:opacity-100  group-hover:sm:w-52"
```suggestion
              className=" h-10 w-10 rounded-full p-4 opacity-0 shadow outline-none transition-all duration-500 ease-in-out group-hover:w-28 group-hover:opacity-100 group-hover:sm:w-52"
```
Attention aux doubles espaces

2023-10-10 15:30 UTC, YDrogen commented on src/components/Sidebar.jsx
> +      </Link>
le `key` doit être dans l'élément direct du map (ici, le `Link`)
Au lieu de rajouter un id (si il sert à rien d'autre), tu peux utiliser l'index du map

2023-10-10 15:30 UTC, YDrogen commented on src/components/Sidebar.jsx
> +const Items = [
Pourquoi `Items` en majuscule ?

2023-10-11 07:28 UTC, Abecker37 approved these changes

2023-10-11 07:37 UTC, YDrogen requested changes
Le nom de la branche n'est toujours pas bon !!!!!!!

2023-10-11 07:37 UTC, YDrogen commented on src/components/Sidebar.jsx
> +];
Du coup tu peux retirer les `id` ici vu que tu les utilise pas

2023-10-11 07:37 UTC, YDrogen commented on src/components/Sidebar.jsx
> +import MenuItem from './Item';
La bonne pratique est
NomDuComponentExporté = NomDuFichier = NomDuComponentImporté
`import MenuItem from './MenuItem';`

2023-10-11 08:07 UTC, jaalazard approved these changes

2023-10-11 09:00 UTC, merged