Feature/animation/carousel
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a pull request #30
Opened 2023-10-12 15:11 UTC by Justicesvr

2023-10-12 15:14 UTC, jaalazard submitted a review, later dismissed

2023-10-13 12:15 UTC, YDrogen requested changes

2023-10-13 12:15 UTC, YDrogen commented on src/pages/Artist.jsx
> +    : '';
Tu peux faire pareil qu'au dessus avec le `?.`; ça évite de faire une ternaire

```suggestion
  const artworkImage = `https://www.artic.edu/iiif/2/${artworks[index]?.image_id}/full/400,/0/default.jpg` || '';
```

2023-10-13 12:15 UTC, YDrogen commented on src/pages/Artist.jsx
> +                  alt={`${artwork.title}`}
```suggestion
                  alt={artwork.title}
```
La template string n'est pas obligatoire si y'a juste une string dedans

2023-10-13 12:31 UTC, Abecker37 approved these changes

2023-10-13 12:37 UTC, YDrogen approved these changes

2023-10-13 12:37 UTC, merged