Feature/filter bar
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a pull request #44
Opened 2023-10-16 15:09 UTC by jaalazard

2023-10-16 15:10 UTC, Abecker37 submitted a review, later dismissed

2023-10-17 13:55 UTC, YDrogen requested changes

2023-10-17 13:55 UTC, YDrogen commented on src/components/FilterBar.jsx
> +import React, { useState } from 'react';
'React' is defined but never used

2023-10-17 13:55 UTC, YDrogen commented on src/pages/Gallery.jsx
> +import { Tally1 } from 'lucide-react';
Peut-être dans une seule ligne
`import { ListFilter, Tally1 } from 'lucide-react';`

2023-10-17 13:55 UTC, YDrogen commented on src/components/NavBar.jsx
> +import { motion, useCycle } from 'framer-motion';
jamais utilisé ?

2023-10-17 13:55 UTC, YDrogen commented on src/components/FilterBar.jsx
> +  ];
Peut être sorti dans d'autres fichiers (`data.js` ?) pour alléger un peu celui-ci
Et vu que ce sont des constantes -> EN_MAJUSCULES

2023-10-17 13:55 UTC, YDrogen commented on src/components/FilterBar.jsx
> +          <div className="menu">
Pourquoi `className="menu"` ?

2023-10-17 13:55 UTC, YDrogen commented on src/components/FilterBar.jsx
> +          <div className="menu">
idem

2023-10-17 13:55 UTC, YDrogen commented on src/components/FilterBar.jsx
> +          <div className="menu">
idem

2023-10-17 13:55 UTC, YDrogen commented on src/components/FilterBar.jsx
> +          <div className="menu">
idem

2023-10-17 15:01 UTC, greegouze approved these changes

2023-10-18 07:19 UTC, YDrogen approved these changes

2023-10-18 07:20 UTC, merged