section 3 home
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a pull request #48
Opened 2023-10-18 15:20 UTC by Abecker37

2023-10-18 15:24 UTC, jaalazard submitted a review, later dismissed

2023-10-19 07:34 UTC, YDrogen requested changes

2023-10-19 07:34 UTC, YDrogen commented on src/pages/Home3.jsx
> +export default function Home3() {
Pourquoi `Home3` ?

2023-10-19 07:38 UTC, Abecker37 commented on src/pages/Home3.jsx
> +export default function Home3() {
parce que c'est la 3 ème partie de la page home

2023-10-19 08:04 UTC, YDrogen commented on src/pages/Home3.jsx
> +export default function Home3() {
Où sont Home1 et Home2 ? 👀

2023-10-19 08:26 UTC, jaalazard approved these changes

2023-10-19 08:40 UTC, closed without merging