footer
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a pull request #53
Opened 2023-10-19 13:01 UTC by Abecker37

2023-10-19 13:02 UTC, Justicesvr submitted a review, later dismissed

2023-10-19 13:06 UTC, Justicesvr approved these changes

2023-10-19 13:28 UTC, YDrogen requested changes

2023-10-19 13:28 UTC, YDrogen commented on src/components/NavBar.jsx
> +        <Footer />
Pourquoi le footer est dans la navbar ?

2023-10-19 13:30 UTC, Abecker37 commented on src/components/NavBar.jsx
> +        <Footer />
pour qu’il soit appeler sur toutes les pages

2023-10-19 13:34 UTC, jaalazard submitted a review, later dismissed

2023-10-19 14:27 UTC, YDrogen commented on src/components/NavBar.jsx
> +        <Footer />
Alors oui mais non; Par définition, un footer n'a rien à faire dans une navbar

2023-10-19 14:27 UTC, Abecker37 commented on src/components/NavBar.jsx
> +        <Footer />
sniff

2023-10-19 14:28 UTC, Abecker37 commented on src/components/NavBar.jsx
> +        <Footer />
je le met où ?

2023-10-20 07:56 UTC, jaalazard commented on src/components/Layout.jsx
J'aime ce composant Layout organisant les composants essentiels de notre application, créant ainsi une structure cohérente pour chaque page, y compris un chargement initial, une barre de navigation, un contenu principal basé sur les routes, et un pied de page.

2023-10-20 07:56 UTC, jaalazard approved these changes

2023-10-20 08:13 UTC, Justicesvr approved these changes

2023-10-20 08:13 UTC, Justicesvr commented on src/router.jsx
bonne idée le component layout qui regroupe la navbar et le footer!

2023-10-20 08:46 UTC, YDrogen approved these changes

2023-10-20 08:47 UTC, merged