Feature/all artist
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a pull request #55
Opened 2023-10-20 08:05 UTC by Justicesvr

2023-10-20 08:26 UTC, Abecker37 approved these changes

2023-10-20 08:26 UTC, Abecker37 commented on src/pages/AllArtists.jsx
Pas mal ton composant ainsi que tes animations !

2023-10-20 08:26 UTC, Abecker37 commented on tailwind.config.js
Pourquoi à tu rajouter ces attributs ?

2023-10-20 08:57 UTC, jaalazard approved these changes

2023-10-20 08:57 UTC, jaalazard commented on src/pages/ArtistCollection.jsx
Cette utilisation de ternaire est fort pertinente

2023-10-20 09:56 UTC, Abecker37 approved these changes

2023-10-20 10:27 UTC, YDrogen requested changes

2023-10-20 10:27 UTC, YDrogen commented on src/pages/AllArtists.jsx
C'est vrai, pourtant y'a quand même des messages en gros
![image](https://github.com/WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a/assets/13053644/1c76cc4a-54ae-4bad-a319-bfde8f5f99c0)

2023-10-20 10:27 UTC, YDrogen commented on src/pages/AllArtists.jsx
Le code des lignes d'oeuvres peut être simplifié pour éviter du code dupliqué 5x
Pour boucler 5x tu peux utiliser ça, ça créé une array de taille 5, donc avec le map ça va boucler 5x
```jsx
{new Array(5).fill().map((_a, i) => (
  {/* Le code d'une ligne */}
))}
```
Pour les classNames tu peux utiliser [`odd:` et `even:`](https://tailwindcss.com/docs/hover-focus-and-other-states#first-last-odd-and-even) pour choisir l'animation gauche/droite une ligne sur deux
Et il faut juste faire un peu de math par rapport à l'index pour afficher 20 par lignes par rapport à l'index `i` (dans l'exemple) de la ligne
Et en bonus sympa, quand tu fera une modif, ça sera directement sur les 5 lignes, et plus besoin de tout changer partout

2023-10-20 10:27 UTC, YDrogen commented on src/router.jsx
> +    element: <AllArtist />,
Pluriel, y'a plusieurs artistes (normalement?)

2023-10-20 10:27 UTC, YDrogen commented on tailwind.config.js
Quels attributs ?

2023-10-20 10:27 UTC, YDrogen commented on src/main.css
> +  }
Pas utilisé ?

2023-10-20 12:10 UTC, Abecker37 commented on tailwind.config.js
ceux la  ```
'scroll-left': 'scroll-left 150s linear infinite',
        'scroll-right': 'scroll-right 150s linear infinite','scroll-left': {
          '0%': {
            transform: 'translateX(0%)',
          },
          '100%': {
            transform: 'translateX(-80%)',
          },
        },
        'scroll-right': {
          '0%': {
            transform: 'translateX(-80%)',
          },
          '100%': {
            transform: 'translateX(0%)',
```

2023-10-20 13:40 UTC, jaalazard approved these changes

2023-10-20 13:40 UTC, jaalazard commented on src/pages/AllArtists.jsx
Excellente façon d'éviter les répétitions !

2023-10-20 14:30 UTC, greegouze approved these changes

2023-10-23 10:20 UTC, jaalazard approved these changes

2023-10-23 10:20 UTC, Abecker37 approved these changes

2023-10-23 13:14 UTC, YDrogen approved these changes

2023-10-23 13:14 UTC, merged