Feature/button next artist
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a pull request #59
Opened 2023-10-20 09:52 UTC by Justicesvr

2023-10-20 10:25 UTC, greegouze approved these changes

2023-10-20 10:25 UTC, greegouze commented on src/pages/ArtistCollection.jsx
> +import { ChevronRight } from 'lucide-react';
tu peux faire { ChevronLeft ,  ChevronRight, X }

2023-10-20 13:41 UTC, jaalazard submitted a review, later dismissed

2023-10-20 14:23 UTC, greegouze approved these changes

2023-10-20 14:23 UTC, greegouze commented on src/pages/ArtistCollection.jsx
> +  const [search] = useState('Hokusai');
sans set ? exotique ^^ utilise une const en attendant

2023-10-23 09:50 UTC, jaalazard approved these changes

2023-10-23 10:14 UTC, Abecker37 approved these changes

2023-10-23 10:17 UTC, Abecker37 submitted a review, later dismissed

2023-10-23 10:17 UTC, Abecker37 commented on src/pages/Artist.jsx
> +  const search = 'Hosukai';
bien vu le changement d'useState a une simple constante

2023-10-23 10:29 UTC, YDrogen requested changes

2023-10-23 10:29 UTC, YDrogen commented on src/pages/ArtistCollection.jsx
> +                      {' '}
Espace inutile ?

2023-10-23 12:47 UTC, jaalazard approved these changes
Excellente manière de supprimer un espace

2023-10-23 12:49 UTC, Abecker37 approved these changes

2023-10-23 12:49 UTC, Abecker37 commented on src/pages/ArtistCollection.jsx
> +                    >
c'est beau sans l'espace

2023-10-23 12:53 UTC, merged