add responsive and clean assets folder
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a pull request #64
Opened 2023-10-25 08:13 UTC by Abecker37

2023-10-25 08:32 UTC, jaalazard approved these changes
C'est bien

2023-10-25 08:32 UTC, greegouze approved these changes

2023-10-25 09:17 UTC, YDrogen requested changes

2023-10-25 09:17 UTC, YDrogen commented on src/components/HomeContent3.jsx
> +        className=" mb-28 flex justify-center md:mb-48"
espace en trop

2023-10-25 09:17 UTC, YDrogen commented on src/components/HomeContent3.jsx
> +        <div className=" text-1xl h-[10%] sm:text-2xl md:max-w-3xl md:text-4xl">
espace en trop

2023-10-25 09:17 UTC, YDrogen commented on src/components/HomeContent3.jsx
> +      <div className="mx-auto flex flex-col-reverse sm:mb-8 sm:flex-row-reverse sm:gap-8 sm:duration-75 ">
espace en trop

2023-10-25 09:41 UTC, greegouze approved these changes

2023-10-26 08:25 UTC, YDrogen approved these changes

2023-10-26 08:25 UTC, merged