Feature/home zone 2
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a pull request #71
Opened 2023-10-27 12:07 UTC by greegouze

2023-10-27 12:12 UTC, jaalazard submitted a review, later dismissed
superbe travail, belle animation!

2023-10-27 12:19 UTC, Justicesvr submitted a review, later dismissed

2023-10-27 12:19 UTC, Justicesvr commented on src/assets/images/home1.png
super ton animation au scroll!

2023-10-30 08:27 UTC, jaalazard approved these changes

2023-10-30 08:33 UTC, Justicesvr submitted a review, later dismissed

2023-10-30 14:08 UTC, YDrogen requested changes

2023-10-30 14:08 UTC, YDrogen commented on src/components/HomeContent2.jsx
> +          ></motion.img>
Tu peux fermer les balises qui ne contiennent pas d'enfants

2023-10-31 08:53 UTC, Abecker37 approved these changes

2023-10-31 11:03 UTC, YDrogen approved these changes

2023-10-31 11:04 UTC, merged