Feature/artwork detail
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a pull request #72
Opened 2023-10-27 12:17 UTC by Justicesvr

2023-10-27 12:19 UTC, jaalazard approved these changes
Sympa cette page détaillant l'oeuvre sélectionnée

2023-10-30 08:28 UTC, jaalazard approved these changes

2023-10-30 08:37 UTC, greegouze approved these changes

2023-10-30 15:22 UTC, YDrogen requested changes

2023-10-30 15:22 UTC, YDrogen commented on src/pages/AllArtists.jsx
> +  const ArtworkGroups = () => {
Ce n'est pas un component, pas besoin de majuscule

2023-10-30 15:22 UTC, YDrogen commented on src/pages/Artworks.jsx
> +            ></img>
Tu peux fermer les balises direct

2023-10-31 08:12 UTC, jaalazard approved these changes

2023-10-31 08:13 UTC, Abecker37 approved these changes

2023-10-31 11:05 UTC, YDrogen approved these changes

2023-10-31 11:05 UTC, merged