Feature/random picture home
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a pull request #78
Opened 2023-10-30 15:50 UTC by Justicesvr

2023-10-30 16:17 UTC, jaalazard submitted a review, later dismissed
J'approuve cette implémentation d'une image au hasard en page d'accueil

2023-10-31 08:31 UTC, Abecker37 submitted a review, later dismissed

2023-10-31 08:31 UTC, Abecker37 commented on tailwind.config.js
Intéressant les images random sur la page home

2023-10-31 11:07 UTC, YDrogen requested changes

2023-10-31 11:07 UTC, YDrogen commented on public/BG8.jpg
Image trop grosse; peut être compressée

2023-10-31 11:14 UTC, Abecker37 approved these changes

2023-10-31 11:16 UTC, YDrogen requested changes

2023-10-31 11:16 UTC, YDrogen commented on public/BG7jpg.jpg
Attention le nom !

2023-10-31 11:20 UTC, Abecker37 approved these changes

2023-10-31 11:32 UTC, YDrogen commented on public/BG8.jpg
C'est pas la bonne image que t'as compressée ? 🤔

2023-10-31 11:32 UTC, YDrogen requested changes

2023-10-31 11:32 UTC, YDrogen commented on public/BG8.jpg
C'est pas la bonne image que t'as compressée ? 🤔

2023-10-31 13:13 UTC, jaalazard approved these changes

2023-11-02 08:20 UTC, YDrogen approved these changes

2023-11-02 08:20 UTC, merged