Release/v0.1.0
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-a pull request #86
Opened 2023-10-31 15:30 UTC by jaalazard

2023-10-31 15:45 UTC, Abecker37 submitted a review, later dismissed
i approve the release

2023-10-31 15:55 UTC, Justicesvr approved these changes

2023-10-31 15:56 UTC, Justicesvr commented
i'm scared

2023-11-02 08:25 UTC, greegouze submitted a review, later dismissed

2023-11-02 13:35 UTC, YDrogen requested changes
- Beaucoup d'erreurs dans la console quand on utilise le site (hors erreurs 404/abort controller)
- Nom des fichiers dans public
  - kebab-case minuscule
  - quand il y'a des chiffres égalements `home-1` par exemple

2023-11-02 13:35 UTC, YDrogen commented on src/main.css
> +@import url('https://fonts.googleapis.com/css2?family=Anton&family=Forum&family=Karla:wght@600&family=La+Belle+Aurore&family=Lexend:wght@400;500;600&family=Lora:wght@400;500;600;700&family=Noto+Serif
Vous n'utilisez pas toutes les fonts importées ici; comparez avec les fonts définies dans `tailwind.config`

2023-11-02 13:35 UTC, YDrogen commented on src/components/ArtistCollection.jsx
> +                  <p>Title :</p>
en anglais, il n'y a pas d'espace avant `:`

2023-11-02 13:35 UTC, YDrogen commented on src/components/ArtistCollection.jsx
> +import { Link } from 'react-router-dom';
une seule ligne possible

2023-11-02 13:35 UTC, YDrogen commented on src/api.jsx
pas de JSX donc pas de `.jsx`

2023-11-02 13:35 UTC, YDrogen commented on src/App.jsx
Fichier inutile

2023-11-02 13:35 UTC, YDrogen commented on src/App.css
Fichier inutile

2023-11-02 16:06 UTC, Abecker37 approved these changes

2023-11-02 17:28 UTC, greegouze submitted a review, later dismissed

2023-11-03 09:00 UTC, Justicesvr submitted a review, later dismissed

2023-11-03 09:15 UTC, YDrogen commented on src/components/NavBar.jsx
> +  }, []);
Justement, le loader vient par dessus, y'a pas besoin de cacher la navbar ?

2023-11-03 09:20 UTC, YDrogen requested changes

2023-11-03 09:20 UTC, YDrogen commented on src/components/HomeContent1.jsx
> +          alt="coucou"
coucou ?

2023-11-03 09:21 UTC, YDrogen commented
+ autre changement au dessus

2023-11-03 09:25 UTC, greegouze submitted a review, later dismissed

2023-11-03 09:25 UTC, Justicesvr submitted a review, later dismissed

2023-11-03 09:25 UTC, Abecker37 approved these changes

2023-11-03 09:29 UTC, Abecker37 approved these changes

2023-11-03 09:32 UTC, Justicesvr approved these changes

2023-11-03 09:33 UTC, greegouze approved these changes

2023-11-03 09:39 UTC, merged